"""models_update

Revision ID: 97f028a56c7a
Revises: 3b9aacfb86e8
Create Date: 2026-09-11 14:30:09.911579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97f028a56c7a'
down_revision: Union[str, Sequence[str], None] = '3b9aacfb86e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_text', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_devices',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'device_id')
    )
    op.add_column('clients', sa.Column('email', sa.String(), nullable=False))
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.create_unique_constraint(None, 'clients', ['email'])
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'changed_at')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'balance')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.drop_column('clients', 'email')
    op.drop_table('client_devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
